- name: "enpass : check pacman (arch)"
  tags:
    - enpass
  shell: pacman -Q enpass-bin
  register: enpass_install
  when: is_arch

- name: "enpass : download package (arch)"
  tags:
    - enpass
  get_url:
    url: https://aur.archlinux.org/cgit/aur.git/snapshot/enpass-bin.tar.gz
    dest: /tmp
  when:
    - is_arch
    - enpass_install.stdout is defined and enpass_install.stdout.find('enpass') < 0

- name: "enpass : unpack the package (arch)"
  tags:
    - enpass
  unarchive:
    src: /tmp/enpass-bin.tar.gz
    dest: /tmp/
    copy: no
  when:
    - is_arch
    - enpass_install.stdout is defined and enpass_install.stdout.find('enpass') < 0
- name: "enpass : build and install (arch)"
  tags:
    - enpass
  shell: cd /tmp/enpass-bin && makepkg -s -i --noconfirm
  when:
    - is_arch
    - enpass_install.stdout is defined and enpass_install.stdout.find('enpass') < 0
