- name: "the The Silver Searcher : install package (Debian based)"
  tags:
    - the-silver-searcher
  become: yes
  package:
    name: silversearcher-ag
    state: present
    update_cache: yes
  when:
    - is_debian

- name: "the The Silver Searcher : install package (Fedora, Arch)"
  tags:
    - the-silver-searcher
  become: yes
  package:
    name: the_silver_searcher
    state: present
    update_cache: yes
  when:
    - is_arch
