- name: "docker : remove old packages (debian)"
  tags:
    - docker
  become: yes
  package:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent
  when: is_debian and not is_wsl

- name: "docker : install dependencies (debian)"
  tags:
    - docker
  become: yes
  package:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
    state: present
    update_cache: yes
  when: is_debian and not is_wsl

- name: "docker : add apt key (debian)"
  tags:
    - docker
  become: yes
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present
  when: is_debian and not is_wsl

- name: "docker : add repository (debian)"
  tags:
    - docker
  become: yes
  apt_repository:
    repo: deb [arch={{ ansible_facts.architecture }}] https://download.docker.com/linux/debian {{ ansible_facts.distribution_release }} stable
    filename: "docker"
  when: is_debian and not is_wsl

- name: "docker : install packages (debian)"
  tags:
    - docker
  become: yes
  package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: yes
  when: is_debian and not is_wsl

- name: "docker : install dependencies (arch)"
  tags:
    - docker
  become: yes
  package:
    name:
      - docker
    state: present
    update_cache: yes
  when: is_arch

- name: "docker : create group"
  tags:
    - docker
  become: yes
  group:
    name: docker
    state: present
  when: is_linux and not is_wsl

- name: "docker : add {{ ansible_facts.user_id }} to docker group"
  tags:
    - docker
  become: yes
  user:
    name: "{{ ansible_facts.user_id }}"
    groups: docker
    append: yes
  when: is_linux and not is_wsl

- name: "docker : enable service"
  tags:
    - docker
  become: yes
  service:
    name: docker
    state: started
    enabled: yes
  when: is_linux and not is_wsl

- name: "docker-compose : download"
  tags:
    - docker-compose
    - docker
  become: yes
  get_url:
    url: https://github.com/docker/compose/releases/download/1.25.3/docker-compose-{{ ansible_facts.system }}-{{ ansible_facts.architecture }}
    dest: /usr/local/bin/docker-compose
    mode: "0555"
  when: is_linux and not is_wsl
