- name: 'zsh : install'
  tags:
    - zsh
  become: yes
  package:
    name:
      - zsh
    state: latest

- name: 'zsh : create directories'
  tags:
    - zsh
    - zsh-config
    - antigen
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - ~/.zsh
    - ~/.zsh.before
    - ~/.zsh.after
    - ~/.zsh.prompts
    - ~/.bin
    - ~/bin
    - ~/.antigen

- name: 'zsh : install antigen'
  tags:
    - zsh
    - zsh-config
    - antigen
  get_url:
    url: https://git.io/antigen
    dest: ~/.antigen/antigen.zsh

- name: 'zsh : create .zshrc'
  tags:
    - zsh
    - zsh-config
  copy:
    content: "for config_file ($HOME/.zsh/*.zsh) source $config_file"
    dest: ~/.zshrc

- name: 'zsh : link configuration'
  tags:
    - zsh
    - zsh-config
  file:
    src: "~/.dotfiles/roles/zsh/files/{{ item }}.zsh"
    dest: "~/.zsh/{{ item }}.zsh"
    state: link
  with_items:
    - 0000_before
    - 0_path
    - antigen
    - aliases
    - ansible
    - colors
    - git
    - history
    - key_bindings
    - prompt
    - rm
    - theme
    - vi_mode
    - zmv
    - zsh_aliases
    - zz_rprompt
    - zzzz_after
