- name: 'firefox : install package (arch)'
  tags:
    - firefox
  become: yes
  package:
    name:
      - firefox
    state: present
    update_cache: yes
  when: ansible_facts.distribution == 'Archlinux'

