- name: 'emacs : install'
  tags:
    - emacs
  become: yes
  package:
    name:
      - emacs
    state: latest

- name: 'emacs : install spacemacs'
  tags:
    - emacs
  git:
    repo: https://github.com/syl20bnr/spacemacs
    dest: ~/.emacs.d

- name: 'emacs : install em scripts'
  tags:
    - emacs
    - em
  file:
    src: ~/.dotfiles/emacs/files/em
    dest: ~/.bin/em
    state: link
    force: yes


- name: 'emacs : add .spacemacs'
  tags:
    - emacs
    - emacs-config
  file:
    src: ~/.dotfiles/emacs/files/spacemacs
    dest: ~/.spacemacs
    state: link
    force: yes
