- name: 'docker : remove old packages (debian)'
  tags:
    - docker
  become: yes
  package:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent
  when: ansible_facts.distribution == 'Debian'

- name: 'docker : install dependencies (debian)'
  tags:
    - docker
  become: yes
  package:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
    state: present
    update_cache: yes
  when: ansible_facts.distribution == 'Debian'

- name: 'docker : add apt key (debian)'
  tags:
    - docker
  become: yes
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present
  when: ansible_facts.distribution == 'Debian'

- name: 'docker : add repository (debian)'
  tags:
    - docker
  become: yes
  apt_repository:
    repo: deb [arch={{ ansible_facts.architecture }}] https://download.docker.com/linux/debian {{ ansible_facts.distribution_release }} stable
    filename: 'docker'
  when: ansible_facts.distribution == 'Debian'

- name: 'docker : install packages'
  tags:
    - docker
  become: yes
  package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: yes

- name: 'docker : create group'
  tags:
    - docker
  become: yes
  group:
    name: docker
    state: present

- name: 'docker : add {{ ansible_facts.user_id }} to docker group'
  tags:
    - docker
  become: yes
  user:
    name: '{{ ansible_facts.user_id }}'
    groups: docker
    append: yes

- name: 'docker : enable service'
  tags:
    - docker
  become: yes
  service:
    name: docker
    state: started
    enabled: yes

- name: 'docker-compose : download'
  tags:
    - docker-compose
    - docker
  become: yes
  get_url:
    url: https://github.com/docker/compose/releases/download/1.25.3/docker-compose-{{ ansible_facts.system }}-{{ ansible_facts.architecture }}
    dest: /usr/local/bin/docker-compose
    mode: '0555'

